### PR TITLE
Changed to wxTextCtrl

### PR DESCRIPTION
**Pull request by adityaj2003**

### CODE REVIEW

**Review by adarshp — CHANGES_REQUESTED** [review]
Hi @adityaj2003  - could you please remove the .DS_Store files from this PR? Also, could you create a .gitignore file at the root of the repo that contains a line to ignore .DS_Store files?

**Review by adarshp — CHANGES_REQUESTED** [review]
@adityaj2003 :

- You don't need the `**/` in front of the `.DS_Store` in the `.gitignore` file.
- There are `.DS_Store` files in the `src` and `templates` directory still - could you please remove them?

**Comment by adityaj2003** [comment]
Hey Adarsh, made the changes.

**Review by adarshp — APPROVED** [review]

**Comment by adarshp** [comment]
> Hey Adarsh, made the changes.

Thanks @adityaj2003 !

**Comment by vincentraymond-ua** [comment]
Hi @adityaj2003, could you please make the following changes:

1. Remove the debugging log statements in ASRWidget.cpp
2. Remove the call to Update() in ASRWidget::OnMessage. This function is called automatically on all widget objects when rendering a new frame. The code for this is in gui.cpp.
3. Make the wxTexCtrl objects read only. It's currently possible to edit/modify the utterances being displayed, which could potentially cause confusion. You can use the SetEditable function of wxTextCtrl objects to do this.

Also, did you run into any issues with the wxtextctrl objects not scrolling properly? I'm seeing some inconsistent behavior on my system, but I'm not sure yet if its a bug or something system specific we need to look into.

**Pull request merged**
